### ISSUE TITLE
Question about the meaning of "skeleton_words"

### ISSUE THREAD

**Issue by blmoistawinde** [HKUST-KnowComp/ASER#10]
Hi, I'm looking at the data, and have some questions about the meaning of certain fields:

Here is the sample eventuality
```
OrderedDict([('_id', 'ce3407c430d7757367196b4222d63bead2cea2d7'),
             ('verbs', 'learn'),
             ('skeleton_words_clean', 'learn python'),
             ('skeleton_words', 'i learn python'),
             ('words', 'i learn python'),
             ('pattern', 's-v-o'),
             ('frequency', 12.0)])
```

I don't understand the relation between `words`, `skeleton_words`, `skeleton_words_clean`. I want to know:

1. is `words` refers to the original lemmatized words extracted from text?
2. What kind of processing has been done to get other values like `skeleton_words` and `skeleton_words_clean`?
3. Is their anyway to distinguish which word belongs to which role (S,V,O) ?

**Comment by seanliu96** [comment]
1. Yes. `words` corresponds to the collections of lemmatized words.
2. Please refer to the updated extraction APIs. `skeleton_words` is the collection of words that match the `pattern`, e.g., "s-v-o".
3. The first version of ASER did not store the dependency edges and pos-tags so that it is not easy to distinguish. ASER 2.0 and later versions have addressed this problem.

Thanks for your questions and suggestions.
