### ISSUE TITLE
Full ASER KG availability

### ISSUE THREAD

**Issue by rndm-jpg** [HKUST-KnowComp/ASER#7]
First of all, thanks a lot for the amazing work in advancing NLP+KG.

Would the full ASER KG be available to download to compare its quality against core?

Thanks again.

**Comment by seanliu96** [comment]
Hi, thanks for your interest of our work. The full KG is extreme large, occupying 66GB disk and 480GB RAM. We spent about 10 days on the bootstrapping experiment and each epoch required more than one day. We are not plaining to release publicly the full KG due to the concern about ease of use. Hope you can understand.

**Comment by vader355** [comment]
> First of all, thanks a lot for the amazing work in advancing NLP+KG.
> 
> 
> 
> Would the full ASER KG be available to download to compare its quality against core?
> 
> 
> 
> Thanks again.
